### ISSUE TITLE
Create sacred branch for 3.18

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/protobuf-feedstock#131]
Python 3.10 migration has started, but protobuf is still on version 3.18.

Packages like tensorflow https://github.com/conda-forge/tensorflow-feedstock/pull/189 are failing to find the right version of protobuf due to the fact that 3.18 isn't built for python 3.10.

Could we create a sacred branch for it?

**Comment by dopplershift** [comment]
If downstream users can't readily bump it forward, then there's no problem creating a branch to build 3.18 for 3.10.

**Comment by hmaarrfk** [comment]
The truth is that protobuf is pinned globally to 3.18
![image](https://user-images.githubusercontent.com/90008/145084469-ed776ea3-b32c-4fcd-b31b-868921f7fe8d.png)

It seems that maybe we can just close out that migration and start a new migration?

**Comment by tswast** [comment]
I'd like to avoid problems like this in future. Ideally the "rebuild Python 3.10" PR should have went towards protobuf==3.18.

Do we avoid merging PRs to update the protobuf package in future until we can coordinate with https://github.com/conda-forge/conda-forge-pinning-feedstock ?

**Comment by dopplershift** [comment]
I don't think that's really necessary. It'd be nice if it'd "just work", but it's not particularly hard to make a branch here and manually add the migration.

**Comment by dopplershift** [comment]
See #135.

**Comment by hmaarrfk** [comment]
migration has started for 3.19. so I'm not so worried anymore
