### ISSUE TITLE
The `meta.yaml` file is missing the `dev_url`

### ISSUE THREAD

**Issue by varlackc** [conda-forge/protobuf-feedstock#139]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
The `meta.yaml` file is missing the `dev_url`
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>
The issue is resolved in the following PR:
https://github.com/conda-forge/protobuf-feedstock/pull/140

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/protobuf-feedstock/pull/140 )
