### ISSUE TITLE
Skipping x64 Python 2.7

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/protobuf-feedstock#17]
We are skipping x64 Python 2.7 due to failing tests. See #16, https://github.com/conda-forge/protobuf-feedstock/pull/16#issuecomment-272472630, and https://ci.appveyor.com/project/conda-forge/protobuf-feedstock/build/1.0.58/job/3wp2baqcaws8u63c

We should keep on eye upstream as that will probably be fixed in a new release.

**Comment by jakirkham** [comment]
[Comment]( https://github.com/conda-forge/protobuf-feedstock/pull/16#issuecomment-272472630 ) from @jjhelmus:

> I found a number of reports of failing unit tests on Windows with protobuf 3.1.0, google/protobuf#2548, google/protobuf#2238 and google/protobuf#2408.  It has been suggested that this may be cause by a "\r\n" vs. "\n" problem and the failures can be ignored.
