### ISSUE TITLE
Build protobuf 3.20 for python 3.11

### ISSUE THREAD

**Issue by maxnoe** [conda-forge/protobuf-feedstock#174]
### Comment:

Dear protobuf feedstock maintainers,

Would it be possible to have a build of protobuf 3.20 for python 3.11? We are still trying to figure out which change in 4.21 broke our package, but we'd like to support python 3.11, so having a 3.20 protobuf for python 3.11 here would be great!

**Comment by xylar** [comment]
It doesn't list 3.11 as supported:
https://github.com/protocolbuffers/protobuf/blob/v3.20.3/python/setup.py#L337

We could try anyway and I'll open a PR but there's a fairly high likelihood that this will require more patching than I'm up for.

**Comment by maxnoe** [comment]
I am using the pypi version of 3.20 with python 3.11....

**Comment by xylar** [comment]
Addressed by #175.  Let's see what happens...

**Comment by maxnoe** [comment]
I am confused, why are there non-any wheels and compiled wheels, doesn't one exclude the other? 

I guess the fact that the 3.11 wheels are missing is just because 3.11 was released after protobuf 3.20...

Anyways, thanks a lot!
