### ISSUE TITLE
Protobuf 25.0 and 25.1 missing

### ISSUE THREAD

**Issue by jamesmyatt** [conda-forge/protobuf-feedstock#210]
Version 25.0 and 25.1 have been released and are on PyPI but not here: https://github.com/protocolbuffers/protobuf/releases, https://pypi.org/project/protobuf/#history

**Comment by jjerphan** [comment]
https://github.com/conda-forge/libprotobuf-feedstock/pull/199 and https://github.com/conda-forge/libprotobuf-feedstock/pull/200 are prerequisites.

**Comment by jamesmyatt** [comment]
OK thanks :)
