### ISSUE TITLE
Build with --cpp_implementation flag?

### ISSUE THREAD

**Issue by hajapy** [conda-forge/protobuf-feedstock#28]
The python package of protobuf has had for a while now the ability to build using a c++ extension to make it much faster than the python implementation. See: https://github.com/google/protobuf/blob/v3.3.0/python/setup.py#L174

It is well known this implementation is much faster, see for example the note in the tensorflow documentation: https://www.tensorflow.org/install/install_linux#protobuf_pip_package_31. I would propose we update our build recipe to include the c++ extension, benefiting tensorflow users and any other users of protobuf doing heavy protobuf serialization/deserialization from python. 

I have an updated build recipe and validated the builds for linux and os x (windows should follow easily). See this PR to my fork (ignoring the files changed for built package destination): https://github.com/hajapy/protobuf-feedstock/pull/1

It's worth noting that I have been using this kind of recipe for 3.1 and 3.2 at my work with tensorflow and other conda-forge packages and not had any issues, so I don't expect this to suddenly break a whole bunch of other packages.  

If the maintainers are in favor of this, I will bring a minimal PR here.

**Comment by jakirkham** [comment]
That was something I tried to a long time ago, but didn't quite get right and haven't had time to play since. If you have time and interest, would encourage you to pursue it here.

**Comment by hajapy** [comment]
Alright good to know it would be welcomed here. I will get a PR in when I get a chance.
