### ISSUE TITLE
Request for a py38 build of protobuf 3.8

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/protobuf-feedstock#75]
Required for https://github.com/conda-forge/mysql-connector-python-feedstock/pull/19

The other option is to bump libprotobuf to 3.10 at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/50052c574f907a0c903f18fcb3d1bcf507ac30d4/recipe/conda_build_config.yaml#L463

**Comment by ocefpaf** [comment]
I'm inclined to bump the pinning. Are you OK with that solution @nehaljwani?

**Comment by nehaljwani** [comment]
Yes, I am okay with that.
